<cfset alreadyExists = {}>
<cfset alreadyExists.Charset = "utf-8">
<cfset alreadyExists.Detail = "">
<cfsavecontent variable="alreadyExists.Filecontent">
<cfoutput><?xml version='1.0' encoding='utf-8' ?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Body>
<idc:service xmlns:idc="http://www.stellent.com/IdcService/" IdcService="CHECKIN_UNIVERSAL">
<idc:document dPublishType="" dFormat="application/pdf" dRevisionID="1" dOriginalName="25-2016-00006.pdf" dDocType="Other" dDocAuthor="jphustman" dRevLabel="1" dUser="jphustman" dPublishState="" dDocName="DOT-JNU_080133" dRevClassID="80133" dStatus="" dOutDate="" dIsWebFormat="0" dInDate="11/2/15 1:30 PM" dLocation="" dID="82056" dReleaseState="E" dCreateDate="11/2/15 1:30 PM" dIsPrimary="1" dExtension="pdf" dDocTitle="25-2016-00006" dDocID="165425">
<idc:field name="xTransaction">eta_workflow</idc:field>
<idc:field name="xSupDateTypes"></idc:field>
<idc:field name="xGISxRef:isSetDefault">1</idc:field>
<idc:field name="wfAction">CHECKIN</idc:field>
<idc:field name="xDocAuthor"></idc:field>
<idc:field name="xTrashDeleteLoc:isSetDefault">1</idc:field>
<idc:field name="xDocAuthor:isSetDefault">1</idc:field>
<idc:field name="xEmailCC"></idc:field>
<idc:field name="xPrimaryParties"></idc:field>
<idc:field name="xReplaces:isSetDefault">1</idc:field>
<idc:field name="xDateValidStart"></idc:field>
<idc:field name="xFormat:isSetDefault">1</idc:field>
<idc:field name="xDateValidStart:isSetDefault">1</idc:field>
<idc:field name="isNew">1</idc:field>
<idc:field name="dLastModifiedDate">3/6/15 2:03 PM</idc:field>
<idc:field name="dWfName">eta_workflow</idc:field>
<idc:field name="xRoutingToken1:isSetDefault">1</idc:field>
<idc:field name="dWfID">28</idc:field>
<idc:field name="xWebFlag"></idc:field>
<idc:field name="dWfStepWeight">1</idc:field>
<idc:field name="dpEvent">OnImport</idc:field>
<idc:field name="xPermitType"></idc:field>
<idc:field name="xStateID2Type:isSetDefault">1</idc:field>
<idc:field name="xSSNSet"></idc:field>
<idc:field name="xStateRegion"></idc:field>
<idc:field name="xPartitionId"></idc:field>
<idc:field name="xAlertText:isSetDefault">1</idc:field>
<idc:field name="isDocProfileDone">1</idc:field>
<idc:field name="xStateID2:isSetDefault">1</idc:field>
<idc:field name="isCollaboration">1</idc:field>
<idc:field name="xLatitude:isSetDefault">1</idc:field>
<idc:field name="xStateID5Type"></idc:field>
<idc:field name="xPermitLicenseNum"></idc:field>
<idc:field name="dCollectionInherit">0</idc:field>
<idc:field name="xStateID1Type:isSetDefault">1</idc:field>
<idc:field name="xSupStateIDs:isSetDefault">1</idc:field>
<idc:field name="xEmailFrom:isSetDefault">1</idc:field>
<idc:field name="xScanDate"></idc:field>
<idc:field name="xSupDate1Type:isSetDefault">1</idc:field>
<idc:field name="dCollectionEnabled">1</idc:field>
<idc:field name="dRawDocID">165425</idc:field>
<idc:field name="xTransactionType:isSetDefault">1</idc:field>
<idc:field name="xPermitType:isSetDefault">1</idc:field>
<idc:field name="xDiscussionCount">0</idc:field>
<idc:field name="isDocProfileUsed">true</idc:field>
<idc:field name="xAssociatedRoles:isSetDefault">1</idc:field>
<idc:field name="xRoutingToken3:isSetDefault">1</idc:field>
<idc:field name="xStateID4Type"></idc:field>
<idc:field name="dActionMillis">123377681</idc:field>
<idc:field name="xMilePost"></idc:field>
<idc:field name="xProjectActivityNum"></idc:field>
<idc:field name="dWfEntryTs">{ts &##39;2015-11-02 13:30:17.681&##39;}</idc:field>
<idc:field name="xComments"></idc:field>
<idc:field name="xFileType"></idc:field>
<idc:field name="dCollectionCreator">jphustman</idc:field>
<idc:field name="xProjectActivityNum:isSetDefault">1</idc:field>
<idc:field name="xDateAccepted"></idc:field>
<idc:field name="xEmailSubject"></idc:field>
<idc:field name="xSupDate1:isSetDefault">1</idc:field>
<idc:field name="xWorkflowTrigger"></idc:field>
<idc:field name="xMilePoint:isSetDefault">1</idc:field>
<idc:field name="xAssociatedParties"></idc:field>
<idc:field name="xPrimaryParties:isSetDefault">1</idc:field>
<idc:field name="xStateID3Type"></idc:field>
<idc:field name="xFacilityID"></idc:field>
<idc:field name="xEmailTo"></idc:field>
<idc:field name="dConversion">ImageThumbnail</idc:field>
<idc:field name="isInfoOnly"></idc:field>
<idc:field name="xStateID5"></idc:field>
<idc:field name="xStateID4"></idc:field>
<idc:field name="xForceFolderSecurity">TRUE</idc:field>
<idc:field name="xStateID3"></idc:field>
<idc:field name="xStateID2"></idc:field>
<idc:field name="dWfStepType">:C:CA:CE:</idc:field>
<idc:field name="xClbraAliasList">@statewide-edocs-admin(RWD),@statewide-eta-review(RWDA)</idc:field>
<idc:field name="xStateID1"></idc:field>
<idc:field name="xDateCreated"></idc:field>
<idc:field name="xTransactionType"></idc:field>
<idc:field name="dWfDirectory">projects</idc:field>
<idc:field name="numlevels">0</idc:field>
<idc:field name="xPublicallyAccessible:isSetDefault">1</idc:field>
<idc:field name="dActionDate">11/2/15 1:30 PM</idc:field>
<idc:field name="dWfStepIsAll">0</idc:field>
<idc:field name="xFormat"></idc:field>
<idc:field name="dAction">Checkin</idc:field>
<idc:field name="xSupStateIDTypes:isSetDefault">1</idc:field>
<idc:field name="xStateID2Type"></idc:field>
<idc:field name="xApprover:isSetDefault">1</idc:field>
<idc:field name="xStateID5Type:isSetDefault">1</idc:field>
<idc:field name="xHidden">FALSE</idc:field>
<idc:field name="xTypeCategory:isSetDefault">1</idc:field>
<idc:field name="dCollectionGUID">9176D945-DB21-9A8B-68F0-B4909C26705A</idc:field>
<idc:field name="xDateIssued"></idc:field>
<idc:field name="xFacilityType"></idc:field>
<idc:field name="xPublicationDate"></idc:field>
<idc:field name="xSupDates:isSetDefault">1</idc:field>
<idc:field name="xRouteType"></idc:field>
<idc:field name="xAssociatedRoles"></idc:field>
<idc:field name="xEmailTo:isSetDefault">1</idc:field>
<idc:field name="xFederalProjectNum"></idc:field>
<idc:field name="xStateID1:isSetDefault">1</idc:field>
<idc:field name="xStateID1Type"></idc:field>
<idc:field name="xTrashDeleter:isSetDefault">1</idc:field>
<idc:field name="xProjectActivityType"></idc:field>
<idc:field name="xComments:isSetDefault">1</idc:field>
<idc:field name="xSupDates"></idc:field>
<idc:field name="xProfileTrigger"></idc:field>
<idc:field name="xEmailCC:isSetDefault">1</idc:field>
<idc:field name="xFileType:isSetDefault">1</idc:field>
<idc:field name="xParcelID"></idc:field>
<idc:field name="xPrimaryRole3"></idc:field>
<idc:field name="xPrimaryRole2"></idc:field>
<idc:field name="xPrimaryRole1"></idc:field>
<idc:field name="dpAction">CheckinNew</idc:field>
<idc:field name="xBorough:isSetDefault">1</idc:field>
<idc:field name="xSupDateTypes:isSetDefault">1</idc:field>
<idc:field name="xTrashDeleteName"></idc:field>
<idc:field name="xClbraUserList">&amp;sysadmin(RWDA),&amp;jphustman(RWDA)</idc:field>
<idc:field name="xFacilityType:isSetDefault">1</idc:field>
<idc:field name="xDateValidEnd"></idc:field>
<idc:field name="xDateAccepted:isSetDefault">1</idc:field>
<idc:field name="isCheckin">1</idc:field>
<idc:field name="xSupDate3"></idc:field>
<idc:field name="xSubject"></idc:field>
<idc:field name="xSupDate2"></idc:field>
<idc:field name="dWfStepName">contribution</idc:field>
<idc:field name="xSupDate1"></idc:field>
<idc:field name="xMilePoint"></idc:field>
<idc:field name="xSupStateIDTypes"></idc:field>
<idc:field name="xRoutingToken3"></idc:field>
<idc:field name="xRoutingToken2"></idc:field>
<idc:field name="xPrimaryRole1:isSetDefault">1</idc:field>
<idc:field name="xRoutingToken1"></idc:field>
<idc:field name="xStateID4:isSetDefault">1</idc:field>
<idc:field name="hasCollectionID">1</idc:field>
<idc:field name="xSelectedWorkflow"></idc:field>
<idc:field name="dWfStepDescription"></idc:field>
<idc:field name="StatusCode">-17</idc:field>
<idc:field name="xLegalDescription"></idc:field>
<idc:field name="xProjectActivityPhase"></idc:field>
<idc:field name="xTypeCategory"></idc:field>
<idc:field name="xPrimaryParty3"></idc:field>
<idc:field name="xPrimaryParty2"></idc:field>
<idc:field name="xPrimaryParty1">321333</idc:field>
<idc:field name="xTrashDeleteName:isSetDefault">1</idc:field>
<idc:field name="xLatitude"></idc:field>
<idc:field name="xAnnouncement">no</idc:field>
<idc:field name="xFederalProjectNum:isSetDefault">1</idc:field>
<idc:field name="xTypeSubcategory:isSetDefault">1</idc:field>
<idc:field name="dParentCollectionID">708</idc:field>
<idc:field name="xReceiveDate:isSetDefault">1</idc:field>
<idc:field name="xTrashDeleteDate"></idc:field>
<idc:field name="xEmailFrom"></idc:field>
<idc:field name="xStateDepartment">Transportation &amp; Public Facilities</idc:field>
<idc:field name="xTrashDeleteLoc">0</idc:field>
<idc:field name="xAlert">no</idc:field>
<idc:field name="xDiscussionType">N/A</idc:field>
<idc:field name="xRouteType:isSetDefault">1</idc:field>
<idc:field name="xSource"></idc:field>
<idc:field name="xLongitude"></idc:field>
<idc:field name="xDateCreated:isSetDefault">1</idc:field>
<idc:field name="xProjectActivityName"></idc:field>
<idc:field name="xBorough"></idc:field>
<idc:field name="xPublicationDate:isSetDefault">1</idc:field>
<idc:field name="xPrimaryRole3:isSetDefault">1</idc:field>
<idc:field name="primaryFile">ram:///25-2016-00006.pdf</idc:field>
<idc:field name="xSupDate3:isSetDefault">1</idc:field>
<idc:field name="dCollectionModifier">jphustman</idc:field>
<idc:field name="xPrimaryParty3:isSetDefault">1</idc:field>
<idc:field name="xDateIssued:isSetDefault">1</idc:field>
<idc:field name="StatusMessage">smessesgInvalid Metadata for &##39;DOT-JNU_080133&##39;. Item with name &##39;25-2016-00006.pdf&##39; already exists in folder &##39;/Projects/eDocs Technical Admin/eDocs Testing/eta-dev/&##39;.</idc:field>
<idc:field name="xProfileTrigger:isSetDefault">1</idc:field>
<idc:field name="xInhibitUpdate">FALSE</idc:field>
<idc:field name="xSupDate3Type"></idc:field>
<idc:field name="xProjectActivityName:isSetDefault">1</idc:field>
<idc:field name="xPublicallyAccessible"></idc:field>
<idc:field name="xStateAgencySection:isSetDefault">1</idc:field>
<idc:field name="xStateID4Type:isSetDefault">1</idc:field>
<idc:field name="xRoute:isSetDefault">1</idc:field>
<idc:field name="dCollectionType">0</idc:field>
<idc:field name="xStateAgencySection"></idc:field>
<idc:field name="dClbraName">PRJ0000028</idc:field>
<idc:field name="dPromptForMetadata">0</idc:field>
<idc:field name="xSubject:isSetDefault">1</idc:field>
<idc:field name="IsWorkflow">1</idc:field>
<idc:field name="xScanBatchName"></idc:field>
<idc:field name="xIsPartOf:isSetDefault">1</idc:field>
<idc:field name="dWorkflowState">E</idc:field>
<idc:field name="xReadOnly">FALSE</idc:field>
<idc:field name="xStateID3Type:isSetDefault">1</idc:field>
<idc:field name="xTrashDeleteDate:isSetDefault">1</idc:field>
<idc:field name="dCollectionID">732</idc:field>
<idc:field name="xSupDate2Type"></idc:field>
<idc:field name="xScannerStationID"></idc:field>
<idc:field name="xDatum"></idc:field>
<idc:field name="xSupDate3Type:isSetDefault">1</idc:field>
<idc:field name="xParcelIDType"></idc:field>
<idc:field name="xEmailSubject:isSetDefault">1</idc:field>
<idc:field name="xParcelIDType:isSetDefault">1</idc:field>
<idc:field name="IsAutoNumber">1</idc:field>
<idc:field name="DocExists"></idc:field>
<idc:field name="xProjectActivityPhase:isSetDefault">1</idc:field>
<idc:field name="xIsPartOf"></idc:field>
<idc:field name="xRoutingToken2:isSetDefault">1</idc:field>
<idc:field name="xApprover"></idc:field>
<idc:field name="xPermitLicenseNum:isSetDefault">1</idc:field>
<idc:field name="primaryFile:path">/opt/stellent/vault/~temp/1054961447.pdf</idc:field>
<idc:field name="xSupDate2Type:isSetDefault">1</idc:field>
<idc:field name="xCity:isSetDefault">1</idc:field>
<idc:field name="xRoute"></idc:field>
<idc:field name="xDateSubmitted:isSetDefault">1</idc:field>
<idc:field name="dCollectionQueries">1</idc:field>
<idc:field name="xSupDate1Type"></idc:field>
<idc:field name="xStateID3:isSetDefault">1</idc:field>
<idc:field name="xSupStateIDs"></idc:field>
<idc:field name="dWfCurrentStepID">67</idc:field>
<idc:field name="xGISxRef"></idc:field>
<idc:field name="xAlertText"></idc:field>
<idc:field name="xFileNumber"></idc:field>
<idc:field name="dWfStepID">67</idc:field>
<idc:field name="xSSNSet:isSetDefault">1</idc:field>
<idc:field name="xAPPxRef"></idc:field>
<idc:field name="xStateRegion:isSetDefault">1</idc:field>
<idc:field name="xTrashDeleter"></idc:field>
<idc:field name="dCollectionOwner">jphustman</idc:field>
<idc:field name="xScanUser"></idc:field>
<idc:field name="xStateDocID"></idc:field>
<idc:field name="xTypeSubcategory"></idc:field>
<idc:field name="xProjectActivityType:isSetDefault">1</idc:field>
<idc:field name="xDateValidEnd:isSetDefault">1</idc:field>
<idc:field name="xLongitude:isSetDefault">1</idc:field>
<idc:field name="StatusReason">csCollectionContentAlreadyExists:25-2016-00006.pdf,/Projects/eDocs Technical Admin/eDocs Testing/eta-dev/</idc:field>
<idc:field name="xFacilityID:isSetDefault">1</idc:field>
<idc:field name="xSelectedWorkflow:isSetDefault">1</idc:field>
<idc:field name="xInhibitUpdate:isSetDefault">1</idc:field>
<idc:field name="xPrimaryRole2:isSetDefault">1</idc:field>
<idc:field name="xParcelID:isSetDefault">1</idc:field>
<idc:field name="dCollectionName">eta-dev</idc:field>
<idc:field name="xDateSubmitted"></idc:field>
<idc:field name="xSupDate2:isSetDefault">1</idc:field>
<idc:field name="xStateID5:isSetDefault">1</idc:field>
<idc:field name="xCity"></idc:field>
<idc:field name="xDatum:isSetDefault">1</idc:field>
<idc:field name="xPrimaryParty2:isSetDefault">1</idc:field>
<idc:field name="xAssociatedParties:isSetDefault">1</idc:field>
<idc:field name="xLegalDescription:isSetDefault">1</idc:field>
<idc:field name="xCollectionID">732</idc:field>
<idc:field name="xSource:isSetDefault">1</idc:field>
<idc:field name="xz_test"></idc:field>
<idc:field name="xFileNumber:isSetDefault">1</idc:field>
<idc:field name="xMilePost:isSetDefault">1</idc:field>
<idc:field name="dChildManipulation">1</idc:field>
<idc:field name="xStorageRule"></idc:field>
<idc:field name="xReceiveDate"></idc:field>
<idc:field name="xReplaces"></idc:field>
<idc:field name="isEditMode">1</idc:field>
</idc:document>
</idc:service>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope></cfoutput>
</cfsavecontent>

<cfset alreadyExists.Header = "HTTP/1.1 200 OK">
<!---<cfset alreadyExists.Content-type = "text/xml; charset=utf-8">--->
<cfset alreadyExists.Connection = "close">
<!---<cfset alreadyExists.Set-cookie = "IntradocLoginState=1; path=/;">--->
<cfset alreadyExists.Date = "Mon, 02 Nov 2015 22:30:18 GMT">
<!---<cfset alreadyExists.Content-length = "14448">--->
<cfset alreadyExists.Server = "Sun-ONE-Web-Server/6.1">
<cfset alreadyExists.Mimetype = "text/xml">
	<cfset alreadyExists.Responseheader.Connection = 'close'>
	<!---<cfset alreadyExists.Responseheader.Content-length = '14448'>--->
	<!---<cfset alreadyExists.Responseheader.Content-type = 'text/xml; charset=utf-8'>--->
	<cfset alreadyExists.Responseheader.Date = 'Mon, 02 Nov 2015 22:30:18 GMT'>
	<cfset alreadyExists.Responseheader.Explanation = 'OK'>
	<cfset alreadyExists.Responseheader.Http_Version = 'HTTP/1.1'>
	<cfset alreadyExists.Responseheader.Server = 'Sun-ONE-Web-Server/6.1'>
	<!---<cfset alreadyExists.Responseheader.Set-cookie = 'IntradocLoginState=1; path=/;'>--->
	<cfset alreadyExists.Responseheader.Status_Code = '200'>
<cfset alreadyExists.Statuscode = '200 OK'>
<cfset alreadyExists.Text = 'YES'>









<cfset success.Charset = "utf-8">
<cfset success.ErrorDetail = "">
<cfsavecontent variable="success.Filecontent">
<cfoutput><?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <idc:service xmlns:idc="http://www.stellent.com/IdcService/" IdcService="CHECKIN_UNIVERSAL">
         <idc:document dPublishType="" dFormat="application/pdf" dRevisionID="1" dProcessingState="C" dSecurityGroup="Projects" dOriginalName="25-2016-00006.pdf" dDocType="Other" dWebExtension="pdf" dDocAuthor="jphustman" dRevLabel="1" dUser="jphustman" dPublishState="" dFileSize="0" dDocName="DOT-JNU_080208" dRevClassID="80208" dStatus="GENWWW" dOutDate="" dIsWebFormat="0" dInDate="11/2/15 3:44 PM" dLocation="" dID="82131" dReleaseState="E" dCreateDate="11/2/15 3:44 PM" dIsPrimary="1" dExtension="pdf" dDocTitle="25-2016-00006" dDocID="165576" dDocAccount="prj/PRJ0000028">
            <idc:field name="xTransaction">eta_workflow</idc:field>
            <idc:field name="xSupDateTypes" />
            <idc:field name="xGISxRef:isSetDefault">1</idc:field>
            <idc:field name="wfAction">CHECKIN</idc:field>
            <idc:field name="xDocAuthor" />
            <idc:field name="xTrashDeleteLoc:isSetDefault">1</idc:field>
            <idc:field name="xDocAuthor:isSetDefault">1</idc:field>
            <idc:field name="xEmailCC" />
            <idc:field name="xPrimaryParties" />
            <idc:field name="xReplaces:isSetDefault">1</idc:field>
            <idc:field name="xDateValidStart" />
            <idc:field name="xFormat:isSetDefault">1</idc:field>
            <idc:field name="xDateValidStart:isSetDefault">1</idc:field>
            <idc:field name="isNew">1</idc:field>
            <idc:field name="dLastModifiedDate">3/6/15 2:03 PM</idc:field>
            <idc:field name="dWfName">eta_workflow</idc:field>
            <idc:field name="xRoutingToken1:isSetDefault">1</idc:field>
            <idc:field name="dWfID">28</idc:field>
            <idc:field name="xWebFlag" />
            <idc:field name="dWfStepWeight">1</idc:field>
            <idc:field name="dpEvent">OnImport</idc:field>
            <idc:field name="noDocLock">1</idc:field>
            <idc:field name="xPermitType" />
            <idc:field name="xStateID2Type:isSetDefault">1</idc:field>
            <idc:field name="xSSNSet" />
            <idc:field name="xStateRegion" />
            <idc:field name="xPartitionId" />
            <idc:field name="xAlertText:isSetDefault">1</idc:field>
            <idc:field name="isDocProfileDone">1</idc:field>
            <idc:field name="xStateID2:isSetDefault">1</idc:field>
            <idc:field name="isCollaboration">1</idc:field>
            <idc:field name="xLatitude:isSetDefault">1</idc:field>
            <idc:field name="xStateID5Type" />
            <idc:field name="xPermitLicenseNum" />
            <idc:field name="dCollectionInherit">0</idc:field>
            <idc:field name="xStateID1Type:isSetDefault">1</idc:field>
            <idc:field name="xSupStateIDs:isSetDefault">1</idc:field>
            <idc:field name="xEmailFrom:isSetDefault">1</idc:field>
            <idc:field name="xScanDate" />
            <idc:field name="xSupDate1Type:isSetDefault">1</idc:field>
            <idc:field name="dCollectionEnabled">1</idc:field>
            <idc:field name="dRawDocID">165575</idc:field>
            <idc:field name="dWfDocState">INPROCESS</idc:field>
            <idc:field name="xTransactionType:isSetDefault">1</idc:field>
            <idc:field name="VaultfilePath">/opt/stellent/vault/other/@prj/@prj0000028/82131.pdf</idc:field>
            <idc:field name="xPermitType:isSetDefault">1</idc:field>
            <idc:field name="xDiscussionCount">0</idc:field>
            <idc:field name="isDocProfileUsed">true</idc:field>
            <idc:field name="xAssociatedRoles:isSetDefault">1</idc:field>
            <idc:field name="xRoutingToken3:isSetDefault">1</idc:field>
            <idc:field name="xStateID4Type" />
            <idc:field name="dActionMillis">127891759</idc:field>
            <idc:field name="xMilePost" />
            <idc:field name="xProjectActivityNum" />
            <idc:field name="dWfEntryTs">{ts '2015-11-02 15:44:31.058'}</idc:field>
            <idc:field name="AliasAccessList">statewide-edocs-admin,7,statewide-eta-review,15</idc:field>
            <idc:field name="dConversionState">New</idc:field>
            <idc:field name="xComments" />
            <idc:field name="xFileType" />
            <idc:field name="lastEntryTs">{ts '2015-11-02 15:44:00.000'}</idc:field>
            <idc:field name="dCollectionCreator">jphustman</idc:field>
            <idc:field name="xProjectActivityNum:isSetDefault">1</idc:field>
            <idc:field name="isStatusChanged">1</idc:field>
            <idc:field name="xDateAccepted" />
            <idc:field name="xEmailSubject" />
            <idc:field name="xSupDate1:isSetDefault">1</idc:field>
            <idc:field name="dRevRank">0</idc:field>
            <idc:field name="xWorkflowTrigger" />
            <idc:field name="xMilePoint:isSetDefault">1</idc:field>
            <idc:field name="xAssociatedParties" />
            <idc:field name="xPrimaryParties:isSetDefault">1</idc:field>
            <idc:field name="xStateID3Type" />
            <idc:field name="xFacilityID" />
            <idc:field name="xEmailTo" />
            <idc:field name="dConversion">ImageThumbnail</idc:field>
            <idc:field name="isInfoOnly" />
            <idc:field name="xStateID5" />
            <idc:field name="xStateID4" />
            <idc:field name="xForceFolderSecurity">TRUE</idc:field>
            <idc:field name="xStateID3" />
            <idc:field name="xStateID2" />
            <idc:field name="dWfStepType">:R:</idc:field>
            <idc:field name="xClbraAliasList">@statewide-edocs-admin(RWD),@statewide-eta-review(RWDA)</idc:field>
            <idc:field name="xStateID1" />
            <idc:field name="xDateCreated" />
            <idc:field name="xTransactionType" />
            <idc:field name="dWfDirectory">projects</idc:field>
            <idc:field name="numlevels">0</idc:field>
            <idc:field name="xPublicallyAccessible:isSetDefault">1</idc:field>
            <idc:field name="dActionDate">11/2/15 3:44 PM</idc:field>
            <idc:field name="dWfStepIsAll">0</idc:field>
            <idc:field name="xFormat" />
            <idc:field name="dAction">Checkin</idc:field>
            <idc:field name="prevReleaseState" />
            <idc:field name="xSupStateIDTypes:isSetDefault">1</idc:field>
            <idc:field name="xStateID2Type" />
            <idc:field name="xApprover:isSetDefault">1</idc:field>
            <idc:field name="xStateID5Type:isSetDefault">1</idc:field>
            <idc:field name="xHidden">FALSE</idc:field>
            <idc:field name="xTypeCategory:isSetDefault">1</idc:field>
            <idc:field name="dCollectionGUID">9176D945-DB21-9A8B-68F0-B4909C26705A</idc:field>
            <idc:field name="xDateIssued" />
            <idc:field name="xFacilityType" />
            <idc:field name="xPublicationDate" />
            <idc:field name="dClbraLongDesc">Admin procedures, certificates, server restarts, etc.</idc:field>
            <idc:field name="xSupDates:isSetDefault">1</idc:field>
            <idc:field name="xRouteType" />
            <idc:field name="xAssociatedRoles" />
            <idc:field name="xEmailTo:isSetDefault">1</idc:field>
            <idc:field name="xFederalProjectNum" />
            <idc:field name="xStateID1:isSetDefault">1</idc:field>
            <idc:field name="xStateID1Type" />
            <idc:field name="xTrashDeleter:isSetDefault">1</idc:field>
            <idc:field name="xProjectActivityType" />
            <idc:field name="xComments:isSetDefault">1</idc:field>
            <idc:field name="xSupDates" />
            <idc:field name="xProfileTrigger" />
            <idc:field name="xEmailCC:isSetDefault">1</idc:field>
            <idc:field name="xFileType:isSetDefault">1</idc:field>
            <idc:field name="xParcelID" />
            <idc:field name="xPrimaryRole3" />
            <idc:field name="xPrimaryRole2" />
            <idc:field name="wfCurrentStepPrefix">Director_Approval@eta_workflow</idc:field>
            <idc:field name="xPrimaryRole1" />
            <idc:field name="dpAction">CheckinNew</idc:field>
            <idc:field name="xBorough:isSetDefault">1</idc:field>
            <idc:field name="xSupDateTypes:isSetDefault">1</idc:field>
            <idc:field name="xTrashDeleteName" />
            <idc:field name="dClbraDefDispAttrs">color_blue</idc:field>
            <idc:field name="WfEditFinished">true</idc:field>
            <idc:field name="xClbraUserList">&amp;sysadmin(RWDA),&amp;jphustman(RWDA)</idc:field>
            <idc:field name="xFacilityType:isSetDefault">1</idc:field>
            <idc:field name="xDateValidEnd" />
            <idc:field name="xDateAccepted:isSetDefault">1</idc:field>
            <idc:field name="wfQueueEnterTs">{ts '2015-11-02 15:44:31.962'}</idc:field>
            <idc:field name="isCheckin">1</idc:field>
            <idc:field name="xSupDate3" />
            <idc:field name="dClbraMailExcludeAll">1</idc:field>
            <idc:field name="xSubject" />
            <idc:field name="xSupDate2" />
            <idc:field name="dWfStepName">Director_Approval</idc:field>
            <idc:field name="xSupDate1" />
            <idc:field name="xMilePoint" />
            <idc:field name="WebfilePath">/opt/stellent/weblayout/groups/projects/@prj/@prj0000028/documents/other/dot-jnu_080208~1.pdf</idc:field>
            <idc:field name="xSupStateIDTypes" />
            <idc:field name="xRoutingToken3" />
            <idc:field name="xRoutingToken2" />
            <idc:field name="xPrimaryRole1:isSetDefault">1</idc:field>
            <idc:field name="xRoutingToken1" />
            <idc:field name="xStateID4:isSetDefault">1</idc:field>
            <idc:field name="hasCollectionID">1</idc:field>
            <idc:field name="xSelectedWorkflow" />
            <idc:field name="dClbraProjLead">sysadmin</idc:field>
            <idc:field name="dWfStepDescription" />
            <idc:field name="StatusCode">0</idc:field>
            <idc:field name="xLegalDescription" />
            <idc:field name="xProjectActivityPhase" />
            <idc:field name="xTypeCategory" />
            <idc:field name="xPrimaryParty3" />
            <idc:field name="xPrimaryParty2" />
            <idc:field name="xPrimaryParty1">321333</idc:field>
            <idc:field name="xTrashDeleteName:isSetDefault">1</idc:field>
            <idc:field name="xLatitude" />
            <idc:field name="xAnnouncement">no</idc:field>
            <idc:field name="xFederalProjectNum:isSetDefault">1</idc:field>
            <idc:field name="xTypeSubcategory:isSetDefault">1</idc:field>
            <idc:field name="dParentCollectionID">708</idc:field>
            <idc:field name="xReceiveDate:isSetDefault">1</idc:field>
            <idc:field name="xTrashDeleteDate" />
            <idc:field name="xEmailFrom" />
            <idc:field name="xStateDepartment">Transportation &amp; Public Facilities</idc:field>
            <idc:field name="xTrashDeleteLoc">0</idc:field>
            <idc:field name="xAlert">no</idc:field>
            <idc:field name="xDiscussionType">N/A</idc:field>
            <idc:field name="xRouteType:isSetDefault">1</idc:field>
            <idc:field name="xSource" />
            <idc:field name="xLongitude" />
            <idc:field name="xDateCreated:isSetDefault">1</idc:field>
            <idc:field name="entryCount">1</idc:field>
            <idc:field name="dWfComputed" />
            <idc:field name="xProjectActivityName" />
            <idc:field name="xBorough" />
            <idc:field name="xPublicationDate:isSetDefault">1</idc:field>
            <idc:field name="xPrimaryRole3:isSetDefault">1</idc:field>
            <idc:field name="primaryFile">ram:///25-2016-00006.pdf</idc:field>
            <idc:field name="xSupDate3:isSetDefault">1</idc:field>
            <idc:field name="dCollectionModifier">jphustman</idc:field>
            <idc:field name="dConvJobID">86065</idc:field>
            <idc:field name="xPrimaryParty3:isSetDefault">1</idc:field>
            <idc:field name="xDateIssued:isSetDefault">1</idc:field>
            <idc:field name="StatusMessage">Successfully checked in content item 'DOT-JNU_080208'.</idc:field>
            <idc:field name="xProfileTrigger:isSetDefault">1</idc:field>
            <idc:field name="xInhibitUpdate">FALSE</idc:field>
            <idc:field name="xSupDate3Type" />
            <idc:field name="xProjectActivityName:isSetDefault">1</idc:field>
            <idc:field name="wfQueueActionState" />
            <idc:field name="wfMessage" />
            <idc:field name="xPublicallyAccessible" />
            <idc:field name="xStateAgencySection:isSetDefault">1</idc:field>
            <idc:field name="xStateID4Type:isSetDefault">1</idc:field>
            <idc:field name="xRoute:isSetDefault">1</idc:field>
            <idc:field name="dCollectionType">0</idc:field>
            <idc:field name="xStateAgencySection" />
            <idc:field name="dClbraName">PRJ0000028</idc:field>
            <idc:field name="dPromptForMetadata">0</idc:field>
            <idc:field name="xSubject:isSetDefault">1</idc:field>
            <idc:field name="IsWorkflow">1</idc:field>
            <idc:field name="xScanBatchName" />
            <idc:field name="xIsPartOf:isSetDefault">1</idc:field>
            <idc:field name="dConvActionDate">11/2/15 3:44 PM</idc:field>
            <idc:field name="dWorkflowState">R</idc:field>
            <idc:field name="xReadOnly">FALSE</idc:field>
            <idc:field name="xStateID3Type:isSetDefault">1</idc:field>
            <idc:field name="xTrashDeleteDate:isSetDefault">1</idc:field>
            <idc:field name="dCollectionID">732</idc:field>
            <idc:field name="xSupDate2Type" />
            <idc:field name="xScannerStationID" />
            <idc:field name="xDatum" />
            <idc:field name="xSupDate3Type:isSetDefault">1</idc:field>
            <idc:field name="xParcelIDType" />
            <idc:field name="xEmailSubject:isSetDefault">1</idc:field>
            <idc:field name="xParcelIDType:isSetDefault">1</idc:field>
            <idc:field name="RenditionId">webViewableFile</idc:field>
            <idc:field name="IsAutoNumber">1</idc:field>
            <idc:field name="wfQueueLastActionTs">{ts '2015-11-02 15:44:31.962'}</idc:field>
            <idc:field name="DocExists" />
            <idc:field name="xProjectActivityPhase:isSetDefault">1</idc:field>
            <idc:field name="xIsPartOf" />
            <idc:field name="xRoutingToken2:isSetDefault">1</idc:field>
            <idc:field name="xApprover" />
            <idc:field name="xPermitLicenseNum:isSetDefault">1</idc:field>
            <idc:field name="primaryFile:path">/opt/stellent/vault/~temp/1054961622.pdf</idc:field>
            <idc:field name="xSupDate2Type:isSetDefault">1</idc:field>
            <idc:field name="xCity:isSetDefault">1</idc:field>
            <idc:field name="dConvStartDate">11/2/15 3:44 PM</idc:field>
            <idc:field name="xRoute" />
            <idc:field name="xDateSubmitted:isSetDefault">1</idc:field>
            <idc:field name="dCollectionQueries">1</idc:field>
            <idc:field name="xSupDate1Type" />
            <idc:field name="UserAccessList">sysadmin,15</idc:field>
            <idc:field name="xStateID3:isSetDefault">1</idc:field>
            <idc:field name="xSupStateIDs" />
            <idc:field name="dWfCurrentStepID">70</idc:field>
            <idc:field name="xGISxRef" />
            <idc:field name="reserveLocation">1</idc:field>
            <idc:field name="xAlertText" />
            <idc:field name="xFileNumber" />
            <idc:field name="dWfStepID">70</idc:field>
            <idc:field name="xSSNSet:isSetDefault">1</idc:field>
            <idc:field name="xAPPxRef" />
            <idc:field name="xStateRegion:isSetDefault">1</idc:field>
            <idc:field name="xTrashDeleter" />
            <idc:field name="dCollectionOwner">jphustman</idc:field>
            <idc:field name="xScanUser" />
            <idc:field name="xStateDocID" />
            <idc:field name="xTypeSubcategory" />
            <idc:field name="xProjectActivityType:isSetDefault">1</idc:field>
            <idc:field name="xDateValidEnd:isSetDefault">1</idc:field>
            <idc:field name="xLongitude:isSetDefault">1</idc:field>
            <idc:field name="xFacilityID:isSetDefault">1</idc:field>
            <idc:field name="xSelectedWorkflow:isSetDefault">1</idc:field>
            <idc:field name="dClbraMailExcludeList" />
            <idc:field name="xInhibitUpdate:isSetDefault">1</idc:field>
            <idc:field name="xPrimaryRole2:isSetDefault">1</idc:field>
            <idc:field name="xParcelID:isSetDefault">1</idc:field>
            <idc:field name="dCollectionName">eta-dev</idc:field>
            <idc:field name="xDateSubmitted" />
            <idc:field name="xSupDate2:isSetDefault">1</idc:field>
            <idc:field name="xStateID5:isSetDefault">1</idc:field>
            <idc:field name="xCity" />
            <idc:field name="xDatum:isSetDefault">1</idc:field>
            <idc:field name="xPrimaryParty2:isSetDefault">1</idc:field>
            <idc:field name="xAssociatedParties:isSetDefault">1</idc:field>
            <idc:field name="xLegalDescription:isSetDefault">1</idc:field>
            <idc:field name="xCollectionID">732</idc:field>
            <idc:field name="xSource:isSetDefault">1</idc:field>
            <idc:field name="xz_test" />
            <idc:field name="xFileNumber:isSetDefault">1</idc:field>
            <idc:field name="xMilePost:isSetDefault">1</idc:field>
            <idc:field name="dChildManipulation">1</idc:field>
            <idc:field name="xStorageRule" />
            <idc:field name="xReceiveDate" />
            <idc:field name="xReplaces" />
            <idc:field name="isEditMode">1</idc:field>
            <idc:resultset name="UserAttribInfo" TotalRows="1">
               <idc:row>
                  <idc:field name="dUserName">jphustman</idc:field>
                  <idc:field name="AttributeInfo">account,prj,15,account,##none,15,role,contributor,15,role,mscve_public,15,role,planning_public,15,role,materials_public,15,role,design_public,15,role,row_public,15,role,admin_public,15,role,airport_public,15,role,gis_public,15,role,construction_public,15,role,advertising_public,15,role,archives_public,15,role,preconstruction_public,15,role,transdata_public,15,role,research_public,15</idc:field>
               </idc:row>
            </idc:resultset>
         </idc:document>
      </idc:service>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope></cfoutput>
</cfsavecontent>
<cfset success.Header = "HTTP/1.1 200 OK Content-type: text/xml; charset=utf-8 Connection: close Set-cookie: IntradocLoginState=1; path=/; Date: Tue, 03 Nov 2015 00:44:32 GMT Content-length: 16720 Server: Sun-ONE-Web-Server/6.1">
<cfset success.Mimetype = "text/xml">
<cfset success.Responseheader = {}>
<cfset success.Responseheader.Connection = "close">
<cfset success.Responseheader.Date = "Tue, 03 Nov 2015 00:44:32 GMT">
<cfset success.Responseheader.Explanation = "OK">
<cfset success.Responseheader.Http_Version = "HTTP/1.1">
<cfset success.Responseheader.Server = "Sun-ONE-Web-Server/6.1">
<cfset success.Responseheader.Status_Code = "200">
<cfset success.Statuscode	= "200 OK">
<cfset success.Text = "YES">
