

/*
expenses=[{"other":"","lodging":"","othertrans":"","taid":"","meals":"","facility":"","explanation":"Depart JNU 1:32pm flDight 65\nArrive ANC 3:26pm L","id":"","expensedate":"11/02/2014","mie":"48","miles":"","surfmileage":""},{"other":"","lodging":"","othertrans":"","taid":"","meals":"","facility":"","explanation":"DLB","id":"","expensedate":"11/3-11/6/14","mie":"240","miles":"","surfmileage":""},{"other":"","lodging":"","othertrans":"","taid":"","meals":"","facility":"","explanation":"DDepart ANC 7:55pm fliLght 70\nArrive JNU 9:32pm B","id":"","expensedate":"11/07/2014","mie":"60","miles":"","surfmileage":""}]&fincodes=[{"taid":"","id":0,"code":"25060210"}]&method=save&onecards=[{"aksasacct":"72111","aksasbatchnum":"B159078-6","taid":"","id":0,"refinvnumber":"0277496832176","amount":"326.90","vendorpvndesc":"Alaska Air","datepaid":"09/29/2014","type":"AIR","aksasrefid":"TKT"},{"aksasacct":"73819","aksasbatchnum":"B159078-7","taid":"","id":0,"refinvnumber":"8900625995828","amount":"9.04","vendorpvndesc":"US Travel","datepaid":"09/29/2014","type":"COMM","aksasrefid":"CO"},{"aksasacct":"72113","aksasbatchnum":"","taid":"","id":0,"refinvnumber":"","amount":"495","vendorpvndesc":"Residence Inn Marriott","datepaid":"11/07/2014","type":"LODG","aksasrefid":"LOD"},{"aksasacct":"72112","aksasbatchnum":"","taid":"","id":0,"refinvnumber":"","amount":"","vendorpvndesc":"Budget-Paid w/Rachel's One card","datepaid":"","type":"SURF","aksasrefid":"CAR"}]&oostate={"debrief":0,"sharing":"","localoption":0,"comments":"","taid":"","groupable":0,"id":"","confname":"","goal":"","localoptionreason":"","beneficial":""}&returnFormat=json&ta={"workdays":"","departurefrom":"","carinc":0,"pvn":"","supervisor":"","perstrav":0,"mileagerate":1,"actualsreq":true,"travadv":0,"worktime":"","destinationto":"","perstravend":"","warrantaddr":0,"travelerid":321333,"returndate":"","id":222,"issubmitted":1,"homezip":"","homeaddress":"","submitted":"September, 17 2015 15:49:39","estcost":"","physaddr":0,"created":"September, 17 2015 15:49:39","taxtravtaxable":"","travpref":"","travelername":"Jeremey P Hustman","dept":"Transportation & Public Facilities","travadvwn":"","perstravairfare":"","tanumber":"25-2016-00006","updated":"","atmwithdrawal":"","edocsid":"","fiscalyear":2016,"processid":2,"ee":1,"departuredate":"","confcom":"","perstravbegin":"","preparerid":321333,"taxtravnontax":"","bu":"GP","destination":"","purpose":"","specialinst":"","instate":1,"homecity":"","deleted":"","homestate":"","hotelinc":0,"edocsname":"","estimatorid":"","dutystation":"Juneau","div":"ISD-INFO SYS SVCS","taxtravtotal":"","travadvwnamt":"","stateauthtrv":"","title":"Analyst/Programmer IV","formtype":"estimate","preparer":"jphustman"}&trws=[{"aksasacct":"72114","taid":"","id":0,"fin":"","amount":"348","type":"M&IE"},{"aksasacct":"72114","taid":"","id":0,"fin":"","amount":"-36","type":"M&IE"}]
*/


describe('Estimate In State Hotel Car', function () {




});
