--------------------------------------------------------
--  File created - Wednesday-November-25-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CONSTANTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."CONSTANTS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ETA_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."ETA_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 421 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EXPENSE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."EXPENSE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 421 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FINANCIAL_CODES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."FINANCIAL_CODES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 281 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MILEAGERATE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."MILEAGERATE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ONECARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."ONECARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 321 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OUTOFSTATE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."OUTOFSTATE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PERSON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."PERSON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 421 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."TA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 341 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TA_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."TA_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 661 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TA_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."TA_SEQ2"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ETADEV"."TRW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 321 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ETA_LOG
--------------------------------------------------------

  CREATE TABLE "ETADEV"."ETA_LOG" 
   (	"CREATED" DATE, 
	"STATUSID" NUMBER(10,0), 
	"PROCESSID" NUMBER(10,0), 
	"TAID" NUMBER(10,0), 
	"TRAVELERID" NUMBER, 
	"ID" NUMBER, 
	"STAFFID" NUMBER, 
	"APPROVED" NUMBER(1,0) DEFAULT 0, 
	"DETAILS" VARCHAR2(512 CHAR), 
	"APPROVERID" NUMBER, 
	"PREPARERID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table EXPENSE
--------------------------------------------------------

  CREATE TABLE "ETADEV"."EXPENSE" 
   (	"ID" NUMBER(10,0), 
	"EXPENSEDATE" VARCHAR2(25 CHAR), 
	"EXPLANATION" VARCHAR2(512 CHAR), 
	"MEALS" VARCHAR2(25 CHAR), 
	"FACILITY" VARCHAR2(25 CHAR), 
	"MILES" NUMBER(10,2), 
	"SURFMILEAGE" NUMBER(10,2), 
	"OTHERTRANS" NUMBER(10,2), 
	"LODGING" NUMBER(10,2), 
	"MIE" NUMBER(10,2), 
	"OTHER" NUMBER(10,2), 
	"TAID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table FINANCIAL_CODES
--------------------------------------------------------

  CREATE TABLE "ETADEV"."FINANCIAL_CODES" 
   (	"ID" NUMBER(10,0), 
	"CODE" VARCHAR2(45 CHAR), 
	"TAID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table MILEAGERATE
--------------------------------------------------------

  CREATE TABLE "ETADEV"."MILEAGERATE" 
   (	"MILEAGERATE" NUMBER(4,3), 
	"EFFECTIVEDATE" DATE DEFAULT NULL, 
	"CHANGEDBY" NUMBER, 
	"ID" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table ONECARD
--------------------------------------------------------

  CREATE TABLE "ETADEV"."ONECARD" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(5 CHAR), 
	"AKSASREFID" VARCHAR2(3 CHAR), 
	"REFINVNUMBER" VARCHAR2(25 CHAR), 
	"VENDORPVNDESC" VARCHAR2(100 CHAR), 
	"AMOUNT" NUMBER(10,2), 
	"DATEPAID" DATE, 
	"AKSASACCT" VARCHAR2(25 CHAR), 
	"AKSASBATCHNUM" VARCHAR2(25 CHAR), 
	"TAID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table OUTOFSTATE
--------------------------------------------------------

  CREATE TABLE "ETADEV"."OUTOFSTATE" 
   (	"ID" NUMBER, 
	"CONFNAME" VARCHAR2(128 BYTE), 
	"GOAL" VARCHAR2(1024 BYTE), 
	"LOCALOPTION" NUMBER DEFAULT 0, 
	"LOCALOPTIONREASON" VARCHAR2(1024 BYTE), 
	"BENEFICIAL" VARCHAR2(1024 BYTE), 
	"SHARING" VARCHAR2(1024 BYTE), 
	"GROUPABLE" NUMBER DEFAULT 0, 
	"DEBRIEF" NUMBER DEFAULT 0, 
	"COMMENTS" VARCHAR2(1024 BYTE), 
	"TAID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "ETADEV"."PERSON" 
   (	"USERNAME" VARCHAR2(20 CHAR), 
	"DIDLOGIN" NUMBER DEFAULT 0, 
	"EIN" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "ETADEV"."STAFF" 
   (	"ID" NUMBER(10,0), 
	"FIRSTNAME" VARCHAR2(45 CHAR), 
	"LASTNAME" VARCHAR2(45 CHAR), 
	"EMAIL" VARCHAR2(45 CHAR), 
	"DATEJOINED" DATE, 
	"DATELEFT" DATE, 
	"OTHERDETAILS" VARCHAR2(255 CHAR), 
	"STAFFROLEID" NUMBER(10,0), 
	"NOTIFY" CHAR(1 CHAR), 
	"USERNAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table STAFF_ROLE
--------------------------------------------------------

  CREATE TABLE "ETADEV"."STAFF_ROLE" 
   (	"ID" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table TA
--------------------------------------------------------

  CREATE TABLE "ETADEV"."TA" 
   (	"ID" NUMBER(10,0), 
	"FISCALYEAR" NUMBER(4,0), 
	"TANUMBER" VARCHAR2(30 CHAR), 
	"EE" CHAR(1 BYTE) DEFAULT 1, 
	"INSTATE" CHAR(1 BYTE) DEFAULT 1, 
	"PHYSADDR" CHAR(1 BYTE) DEFAULT 0, 
	"WARRANTADDR" CHAR(1 BYTE) DEFAULT 0, 
	"PVN" VARCHAR2(20 CHAR), 
	"TRAVELERNAME" VARCHAR2(100 CHAR), 
	"TITLE" VARCHAR2(100 CHAR), 
	"DEPT" VARCHAR2(100 CHAR), 
	"DIV" VARCHAR2(100 CHAR), 
	"BU" VARCHAR2(100 CHAR), 
	"DUTYSTATION" VARCHAR2(100 CHAR), 
	"HOMEADDRESS" VARCHAR2(100 CHAR), 
	"HOMECITY" VARCHAR2(45 CHAR), 
	"HOMESTATE" VARCHAR2(20 CHAR), 
	"HOMEZIP" VARCHAR2(10 CHAR), 
	"WORKDAYS" VARCHAR2(45 CHAR), 
	"WORKTIME" VARCHAR2(45 CHAR), 
	"DESTINATION" VARCHAR2(512 CHAR), 
	"TRAVPREF" VARCHAR2(512 CHAR), 
	"DEPARTUREFROM" VARCHAR2(60 CHAR), 
	"DEPARTUREDATE" DATE, 
	"RETURNDATE" DATE, 
	"PURPOSE" VARCHAR2(1024 CHAR), 
	"ESTCOST" NUMBER(*,0), 
	"ACTUALSREQ" CHAR(1 BYTE) DEFAULT 0, 
	"TRAVADV" CHAR(1 BYTE) DEFAULT 0, 
	"PERSTRAV" CHAR(1 BYTE) DEFAULT 0, 
	"PERSTRAVBEGIN" DATE, 
	"PERSTRAVEND" DATE, 
	"PERSTRAVAIRFARE" NUMBER(*,0), 
	"STATEAUTHTRV" VARCHAR2(1000 CHAR), 
	"HOTELINC" CHAR(1 BYTE) DEFAULT 0, 
	"CARINC" CHAR(1 BYTE) DEFAULT 0, 
	"CONFCOM" VARCHAR2(1000 CHAR), 
	"SUPERVISOR" VARCHAR2(50 CHAR), 
	"ISSUBMITTED" CHAR(1 BYTE) DEFAULT 0, 
	"SPECIALINST" VARCHAR2(1000 CHAR), 
	"CREATED" DATE, 
	"UPDATED" DATE, 
	"SUBMITTED" DATE, 
	"DELETED" DATE, 
	"TRAVELERID" FLOAT(126), 
	"PREPARERID" FLOAT(126), 
	"TRAVADVWN" VARCHAR2(20 CHAR), 
	"TRAVADVWNAMT" NUMBER(*,0), 
	"ATMWITHDRAWAL" NUMBER(*,0), 
	"EDOCSID" VARCHAR2(20 CHAR), 
	"EDOCSNAME" VARCHAR2(20 CHAR), 
	"DESTINATIONTO" VARCHAR2(512 CHAR), 
	"ESTIMATORID" FLOAT(126), 
	"TAXTRAVNONTAX" NUMBER(*,0), 
	"TAXTRAVTAXABLE" NUMBER(*,0), 
	"TAXTRAVTOTAL" NUMBER(*,0), 
	"PROCESSID" FLOAT(126), 
	"MILEAGERATE" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table TA_STATUS
--------------------------------------------------------

  CREATE TABLE "ETADEV"."TA_STATUS" 
   (	"ID" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table TRW
--------------------------------------------------------

  CREATE TABLE "ETADEV"."TRW" 
   (	"ID" NUMBER, 
	"FIN" NUMBER, 
	"TYPE" VARCHAR2(8 CHAR), 
	"AMOUNT" NUMBER, 
	"AKSASACCT" VARCHAR2(5 BYTE), 
	"TAID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Table WORKFLOW_PROCESSES
--------------------------------------------------------

  CREATE TABLE "ETADEV"."WORKFLOW_PROCESSES" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
REM INSERTING into ETADEV.ETA_LOG
SET DEFINE OFF;
REM INSERTING into ETADEV.EXPENSE
SET DEFINE OFF;
REM INSERTING into ETADEV.FINANCIAL_CODES
SET DEFINE OFF;
REM INSERTING into ETADEV.MILEAGERATE
SET DEFINE OFF;
Insert into ETADEV.MILEAGERATE (MILEAGERATE,EFFECTIVEDATE,CHANGEDBY,ID) values (0.575,to_date('01-JAN-15','DD-MON-RR'),321333,1);
REM INSERTING into ETADEV.ONECARD
SET DEFINE OFF;
REM INSERTING into ETADEV.OUTOFSTATE
SET DEFINE OFF;
REM INSERTING into ETADEV.PERSON
SET DEFINE OFF;
REM INSERTING into ETADEV.STAFF
SET DEFINE OFF;
Insert into ETADEV.STAFF (ID,FIRSTNAME,LASTNAME,EMAIL,DATEJOINED,DATELEFT,OTHERDETAILS,STAFFROLEID,NOTIFY,USERNAME) values (0,'Nobody','Jones','nobody@alaska.gov',to_date('21-DEC-12','DD-MON-RR'),null,null,1,'Y',null);
Insert into ETADEV.STAFF (ID,FIRSTNAME,LASTNAME,EMAIL,DATEJOINED,DATELEFT,OTHERDETAILS,STAFFROLEID,NOTIFY,USERNAME) values (321333,'Jeremey','Hustman','jeremey.hustman@alaska.gov',to_date('11-AUG-14','DD-MON-RR'),null,null,1,'Y','jphustman');
Insert into ETADEV.STAFF (ID,FIRSTNAME,LASTNAME,EMAIL,DATEJOINED,DATELEFT,OTHERDETAILS,STAFFROLEID,NOTIFY,USERNAME) values (289377,'Nino','Bohulano','fernino.bohulano@alaska.gov',to_date('21-OCT-14','DD-MON-RR'),null,null,1,'N',null);
Insert into ETADEV.STAFF (ID,FIRSTNAME,LASTNAME,EMAIL,DATEJOINED,DATELEFT,OTHERDETAILS,STAFFROLEID,NOTIFY,USERNAME) values (261130,'Rachel','Kindred','rachel.kindred@alaska.gov',to_date('21-OCT-14','DD-MON-RR'),null,null,1,'N',null);
Insert into ETADEV.STAFF (ID,FIRSTNAME,LASTNAME,EMAIL,DATEJOINED,DATELEFT,OTHERDETAILS,STAFFROLEID,NOTIFY,USERNAME) values (325417,'Brittany','Weideman','brittany.weideman@alaska.gov',to_date('21-OCT-14','DD-MON-RR'),null,null,1,'N',null);
Insert into ETADEV.STAFF (ID,FIRSTNAME,LASTNAME,EMAIL,DATEJOINED,DATELEFT,OTHERDETAILS,STAFFROLEID,NOTIFY,USERNAME) values (231749,'Wendy','Parker','wendy.parker@alaska.gov',to_date('21-APR-15','DD-MON-RR'),null,null,1,'N',null);
REM INSERTING into ETADEV.STAFF_ROLE
SET DEFINE OFF;
Insert into ETADEV.STAFF_ROLE (ID,DESCRIPTION) values (1,'Travel Planner');
Insert into ETADEV.STAFF_ROLE (ID,DESCRIPTION) values (2,'Divisional Approver');
Insert into ETADEV.STAFF_ROLE (ID,DESCRIPTION) values (3,'Departmental Approver');
REM INSERTING into ETADEV.TA
SET DEFINE OFF;
REM INSERTING into ETADEV.TA_STATUS
SET DEFINE OFF;
Insert into ETADEV.TA_STATUS (ID,DESCRIPTION) values (1,'Pre-Trip');
Insert into ETADEV.TA_STATUS (ID,DESCRIPTION) values (2,'Trip');
Insert into ETADEV.TA_STATUS (ID,DESCRIPTION) values (3,'Post-Trip');
Insert into ETADEV.TA_STATUS (ID,DESCRIPTION) values (4,'Finalized');
REM INSERTING into ETADEV.TRW
SET DEFINE OFF;
REM INSERTING into ETADEV.WORKFLOW_PROCESSES
SET DEFINE OFF;
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (12,'Completed');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (0,'Deleted');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (1,'Start TA');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (2,'Sent to Travel Planner');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (3,'E-Travel Itinerary Research');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (4,'Rejected');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (5,'Waiting for Div Approval');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (6,'Waiting for Dept Approval');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (7,'Travel Envelope Preparation');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (8,'Finalize TA');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (9,'TA Submission');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (10,'Reconciliation');
Insert into ETADEV.WORKFLOW_PROCESSES (ID,NAME) values (11,'Submit for Certification');
--------------------------------------------------------
--  DDL for Index EXPENSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."EXPENSE_PK" ON "ETADEV"."EXPENSE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index STAFFROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."STAFFROLE_PK" ON "ETADEV"."STAFF_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index FINANCIALCODES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."FINANCIALCODES_PK" ON "ETADEV"."FINANCIAL_CODES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index TA_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."TA_STATUS_PK" ON "ETADEV"."TA_STATUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index STAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."STAFF_PK" ON "ETADEV"."STAFF" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index TAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."TAS_PK" ON "ETADEV"."TA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."PERSON_PK" ON "ETADEV"."PERSON" ("EIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index OUTOFSTATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."OUTOFSTATE_PK" ON "ETADEV"."OUTOFSTATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index TRW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."TRW_PK" ON "ETADEV"."TRW" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index MILEAGERATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."MILEAGERATE_PK" ON "ETADEV"."MILEAGERATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index ETA_LOG_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."ETA_LOG_PK1" ON "ETADEV"."ETA_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index ONECARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."ONECARD_PK" ON "ETADEV"."ONECARD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  DDL for Index WORKFLOW_PROCESSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETADEV"."WORKFLOW_PROCESSES_PK" ON "ETADEV"."WORKFLOW_PROCESSES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA" ;
--------------------------------------------------------
--  Constraints for Table WORKFLOW_PROCESSES
--------------------------------------------------------

  ALTER TABLE "ETADEV"."WORKFLOW_PROCESSES" ADD CONSTRAINT "WORKFLOW_PROCESSES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXPENSE
--------------------------------------------------------

  ALTER TABLE "ETADEV"."EXPENSE" ADD CONSTRAINT "EXPENSE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "ETADEV"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("EIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ONECARD
--------------------------------------------------------

  ALTER TABLE "ETADEV"."ONECARD" ADD CONSTRAINT "ONECARD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRW
--------------------------------------------------------

  ALTER TABLE "ETADEV"."TRW" ADD CONSTRAINT "TRW_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ETA_LOG
--------------------------------------------------------

  ALTER TABLE "ETADEV"."ETA_LOG" ADD CONSTRAINT "ETA_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "ETADEV"."STAFF" ADD CONSTRAINT "STAFF_CHK1" CHECK (notify in ('N','Y')) ENABLE;
 
  ALTER TABLE "ETADEV"."STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MILEAGERATE
--------------------------------------------------------

  ALTER TABLE "ETADEV"."MILEAGERATE" ADD CONSTRAINT "MILEAGERATE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TA
--------------------------------------------------------

  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK1" CHECK (instate in (0,1)) ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK10" CHECK (warrantaddr in (0,1)) ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK2" CHECK (ee in (0,1)
) ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK3" CHECK (actualsreq in (0,1)) ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK4" CHECK (carinc in (0,1)) ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK5" CHECK (hotelinc in (0,1)) ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK6" CHECK (issubmitted in (0,1)) ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK7" CHECK (perstrav in (0,1)) ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK8" CHECK (physaddr in (0,1)) ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_CHK9" CHECK (travadv in (0,1)) ENABLE;
--------------------------------------------------------
--  Constraints for Table TA_STATUS
--------------------------------------------------------

  ALTER TABLE "ETADEV"."TA_STATUS" ADD CONSTRAINT "TA_STATUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF_ROLE
--------------------------------------------------------

  ALTER TABLE "ETADEV"."STAFF_ROLE" ADD CONSTRAINT "STAFFROLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OUTOFSTATE
--------------------------------------------------------

  ALTER TABLE "ETADEV"."OUTOFSTATE" ADD CONSTRAINT "OUTOFSTATE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FINANCIAL_CODES
--------------------------------------------------------

  ALTER TABLE "ETADEV"."FINANCIAL_CODES" ADD CONSTRAINT "FINANCIALCODES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAVAUTH_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ETA_LOG
--------------------------------------------------------

  ALTER TABLE "ETADEV"."ETA_LOG" ADD CONSTRAINT "ETA_LOG_FK1" FOREIGN KEY ("TRAVELERID")
	  REFERENCES "ETADEV"."PERSON" ("EIN") ENABLE;
 
  ALTER TABLE "ETADEV"."ETA_LOG" ADD CONSTRAINT "ETA_LOG_FK2" FOREIGN KEY ("TAID")
	  REFERENCES "ETADEV"."TA" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "ETADEV"."ETA_LOG" ADD CONSTRAINT "ETA_LOG_FK3" FOREIGN KEY ("PROCESSID")
	  REFERENCES "ETADEV"."WORKFLOW_PROCESSES" ("ID") ENABLE;
 
  ALTER TABLE "ETADEV"."ETA_LOG" ADD CONSTRAINT "ETA_LOG_FK4" FOREIGN KEY ("STATUSID")
	  REFERENCES "ETADEV"."TA_STATUS" ("ID") ENABLE;
 
  ALTER TABLE "ETADEV"."ETA_LOG" ADD CONSTRAINT "ETA_LOG_FK5" FOREIGN KEY ("STAFFID")
	  REFERENCES "ETADEV"."STAFF" ("ID") ENABLE;
 
  ALTER TABLE "ETADEV"."ETA_LOG" ADD CONSTRAINT "ETA_LOG_FK6" FOREIGN KEY ("APPROVERID")
	  REFERENCES "ETADEV"."STAFF" ("ID") ENABLE;
 
  ALTER TABLE "ETADEV"."ETA_LOG" ADD CONSTRAINT "ETA_LOG_FK7" FOREIGN KEY ("PREPARERID")
	  REFERENCES "ETADEV"."PERSON" ("EIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXPENSE
--------------------------------------------------------

  ALTER TABLE "ETADEV"."EXPENSE" ADD CONSTRAINT "EXPENSE_FK1" FOREIGN KEY ("TAID")
	  REFERENCES "ETADEV"."TA" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCIAL_CODES
--------------------------------------------------------

  ALTER TABLE "ETADEV"."FINANCIAL_CODES" ADD CONSTRAINT "FINANCIALCODES_FK1" FOREIGN KEY ("TAID")
	  REFERENCES "ETADEV"."TA" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ONECARD
--------------------------------------------------------

  ALTER TABLE "ETADEV"."ONECARD" ADD CONSTRAINT "ONECARD_FK1" FOREIGN KEY ("TAID")
	  REFERENCES "ETADEV"."TA" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OUTOFSTATE
--------------------------------------------------------

  ALTER TABLE "ETADEV"."OUTOFSTATE" ADD CONSTRAINT "OUTOFSTATE_FK1" FOREIGN KEY ("TAID")
	  REFERENCES "ETADEV"."TA" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "ETADEV"."STAFF" ADD CONSTRAINT "STAFF_FK1" FOREIGN KEY ("STAFFROLEID")
	  REFERENCES "ETADEV"."STAFF_ROLE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TA
--------------------------------------------------------

  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_FK1" FOREIGN KEY ("TRAVELERID")
	  REFERENCES "ETADEV"."PERSON" ("EIN") ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_FK2" FOREIGN KEY ("ESTIMATORID")
	  REFERENCES "ETADEV"."STAFF" ("ID") ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_FK3" FOREIGN KEY ("PREPARERID")
	  REFERENCES "ETADEV"."PERSON" ("EIN") ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_FK4" FOREIGN KEY ("PROCESSID")
	  REFERENCES "ETADEV"."WORKFLOW_PROCESSES" ("ID") ENABLE;
 
  ALTER TABLE "ETADEV"."TA" ADD CONSTRAINT "TA_FK5" FOREIGN KEY ("MILEAGERATE")
	  REFERENCES "ETADEV"."MILEAGERATE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRW
--------------------------------------------------------

  ALTER TABLE "ETADEV"."TRW" ADD CONSTRAINT "TRW_FK1" FOREIGN KEY ("TAID")
	  REFERENCES "ETADEV"."TA" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONSTANTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."CONSTANTS_TRG" 
BEFORE INSERT ON MILEAGERATE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."CONSTANTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ETA_LOG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."ETA_LOG" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select ETA_LOG_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ETADEV"."ETA_LOG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EXPENSE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."EXPENSE_TRG" 
BEFORE INSERT ON EXPENSE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EXPENSE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."EXPENSE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FINANCIAL_CODES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."FINANCIAL_CODES_TRG" 
BEFORE INSERT ON FINANCIAL_CODES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT FINANCIAL_CODES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."FINANCIAL_CODES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MILEAGERATE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."MILEAGERATE_TRG" 
BEFORE INSERT ON MILEAGERATE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MILEAGERATE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."MILEAGERATE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ONECARD_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."ONECARD_TRG" 
BEFORE INSERT ON ONECARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ONECARD_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."ONECARD_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OUTOFSTATE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."OUTOFSTATE_TRG" 
BEFORE INSERT ON OUTOFSTATE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OUTOFSTATE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."OUTOFSTATE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."TA_TRG" 
  BEFORE INSERT ON "TA"
  REFERENCING FOR EACH ROW
  BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."TA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TA_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."TA_TRG1" 
BEFORE INSERT ON TA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."TA_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TA_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."TA_TRG2" 
BEFORE INSERT ON TA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."TA_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRW_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ETADEV"."TRW_TRG" 
  BEFORE INSERT ON "TRW"
  REFERENCING FOR EACH ROW
  BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TRW_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ETADEV"."TRW_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Function SQUIRREL_GET_ERROR_OFFSET
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "ETADEV"."SQUIRREL_GET_ERROR_OFFSET" (query IN varchar2) return number authid current_user is      l_theCursor     integer default dbms_sql.open_cursor;      l_status        integer; begin          begin          dbms_sql.parse(  l_theCursor, query, dbms_sql.native );          exception                  when others then l_status := dbms_sql.last_error_position;          end;          dbms_sql.close_cursor( l_theCursor );          return l_status; end; 
/
